// Code generated by "stringer -type=Operator"; DO NOT EDIT.

package gonet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpNone-0]
	_ = x[OpPlus-1]
	_ = x[OpMultiply-2]
	_ = x[OpRelu-3]
	_ = x[OpSigmoid-4]
	_ = x[OpTanh-5]
	_ = x[OpSoftmax-6]
}

const _Operator_name = "OpNoneOpPlusOpMultiplyOpReluOpSigmoidOpTanhOpSoftmax"

var _Operator_index = [...]uint8{0, 6, 12, 22, 28, 37, 43, 52}

func (i Operator) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Operator_index)-1 {
		return "Operator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operator_name[_Operator_index[idx]:_Operator_index[idx+1]]
}
